name: Deploy Documentation

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: squidfunk/mkdocs-material

    steps:
    - run: |
        mkdocs build 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{secrets.ACTIONS_DEPLOY_KEY}}
        # PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./site
      with:
        keepFiles: true
        
    - uses: actions/checkout@v1
    - name: Building the documentation
      run: |
        mkdocs build 
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{secrets.FTP_SERVER}}
        FTP_USERNAME: ${{secrets.FTP_USERNAME}}
        FTP_PASSWORD: ${{secrets.FTP_PASSWORD}}
        LOCAL_DIR: site
        #ARGS: --delete        
